### PR TITLE
Fix loading flash

### LINKED ISSUE #323: "Loading..." text flashes on non NP pages
How to reproduce:

1. Go to https://hollowverse.com/Tom_Hanks
1. Position your cursor on "Hollowverse" logo in the navbar
1. While keeping your eye on the top-left corner of the viewport, click on "Hollowverse" logo in the navbar

You will see "Loading..." text flashing in the top left corner of the view port under the navbar.

### PR DESCRIPTION
**Pull request by wholesomedev**
I've used our loading spinner as a substitute for the "Loading..." flash. I changed the CSS of the loading spinner to make it always vertically and horizontally centered within its parent.

Fixes #323

### CODE REVIEW

File: src/app/__tests__/notablePersonPage.ts [hunk 1]
```diff
@@ -25,7 +26,11 @@ describe('Notable Person page', () => {
       });
     });
 
-    it('has notable person name', () => {
+    it('has notable person name', async () => {
+      // We force a 300 ms min delay in our loadable components for better UX. The delay below ensures
+      // that the loadable component has rendered before making the assertion.
+      await delay(301);
```
Comment (wholesomedev) [inline src/app/__tests__/notablePersonPage.ts]: I'm not sure how to better handle this case

Comment (forabi) [reply src/app/__tests__/notablePersonPage.ts]: I think we should go back to using a custom routes map for tests which uses the actual, resolved components instead of the loadable ones. Anyway, this needs to be rebased as I've switched to using `react-loadable` because `react-universal-components` is for SSR apps and it didn't work well with Webpack 4 (it could have worked client-side only with Webpack 3). I'll rebase and make the necessary changes.

**Review by forabi — APPROVED** [review]

**Review by wholesomedev — COMMENTED** [review]
Awesome, thanks!
